version: "3.8"
services:
  botman:
    restart: unless-stopped
    build:
      context: botman
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: botman
    environment:
        DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
        DISCORD_BOT_OWNER_ID: ${DISCORD_BOT_OWNER_ID}
        LAVALINK_SERVER_PASSWORD: ${LAVALINK_SERVER_PASSWORD}
        LAVALINK_SERVER_HOST: lavalink
        LAVALINK_SERVER_PORT: 2333
    depends_on: 
      - lavalink
    networks:
      - lavalink

  lavalink:
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: lavalink
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./lavalink/lavalink_application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink:
    driver: bridge